[package]
name = "rust-time-series-objects"
version = "0.1.0"
edition = "2024"

[lib]
name = "rust_time_series_objects"
crate-type = ["cdylib"]

[dependencies]

[dependencies.pyo3]
version = "0.27.0"
features = ["abi3-py38"]